apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: G1
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: G1

