apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-pod
    app: G1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: G1
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: G1
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports: 
            - containerPort: 5432