apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-pod
    app: G1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: G1
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: G1
    spec:
      containers:
        - name: redis
          image: redis
          ports: 
            - containerPort: 6379