apiVersion: v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-pod
    app: G1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: G1 
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: G1
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker